Added uploading the report

diff --git a/.github/workflows/makefile.yml b/.github/workflows/makefile.yml
--- a/.github/workflows/makefile.yml
+++ b/.github/workflows/makefile.yml
@@ -15,9 +15,15 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: install cpputest
+    - name: Install cpputest
       run: sudo apt install -y cpputest
-    - uses: actions/checkout@v4
+    - name: Checkout
+      uses: actions/checkout@v4
     - name: Run tests
       working-directory: ./Code/Encoder_Controller/tests
       run: make test
+    - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v6
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './Code/Encoder_Controller/tests/*.xml'
